### ISSUE TITLE
Logbook 1

### ISSUE THREAD

**Issue by sahilgg60** [HeroGG21/BotBazaar#1]
## Log: 1
**Meeting No:** 1
**Date:** 2024-11-15
**Start Time:** 11 A.M
**End Time:** 11:30 A.M
## Items Discussed
- **Reviewed the proposal report:** Update on methodology (from scrum into incremental) and Work Breakdown Structure (documentation and database-related contents). Gantt Chart timeline and Work Breakdown Structure (WBS) need to be kept in mind.
- Discussion on the grading criteria for the proposal report.
- **GitHub Setup:** We were instructed to create a GitHub repository for storing our project code. We used README.md files provided by GitHub for an  overview and understanding of our project. The Issues section on the repository helps keep track of our tasks before completion. 
- Business rules and defining actors, as well as their properties and limitations.
- Entity Relation Diagram (ERD) of the project.
## Achievements

- [x]  Created a GitHub repository for the project along with all the resources of the project.

- [x]  Completion of Business rules for the project.

- [x]  Successfully created the Entity Relationship Diagram (ERD).

## Problem (if any)

1.  **Business Rules:**
- A situation where multiple discounts on a single product can arise leading to a reduction in profit margin. Thus, making a rule for allowing only one discount per order.
2. **Creating ERD:**
- Confusion on whether to create a "**discount**" table for discount offers on different products or just put discount offers on selected products only. Thus, created a separate **"discount"** table for reusability and flexibility in managing discount codes. 
## Tasks for the Next Meeting:
- Wireframes and UI designs using Figma.
- Creating tables for all defined entities.
- Research and installation of debugging packages in VS Code.
- Installation of Language Server Extensions in Visual Studio Code for checking syntax errors and automatic fixes for common issues.
