### ISSUE TITLE
LogBook 2

### ISSUE THREAD

**Issue by sahilgg60** [HeroGG21/BotBazaar#2]
## Log: 2
**Meeting No:** 2
**Date:** 2024-11-28
**Start Time:** 11 A.M
**End Time:** 12:00 P.M

## Items Discussed

1.  Language Server Protocol(LSP) and extensions in VS Code:
     -  Discussed about the features of the Language Server Protocol(LSP).
     -  Install VS Code extensions that provide language-specific features for checking syntax errors and linting codes.
2. Debugging tools and practices:
    -  Learned and discussed about debugging tools and their integrations.
3. GitHub Issue Tracking:
   -  Learned about **commit links**  and added them to track changes in tasks in GitHub issues.
   -  Upload the photo of the signed logbook in the comment section of every issue for future ease of access.
4. Loosely Typed vs. Strongly Typed Languages:
    - Discussed the differences between loosely typed languages ( e.g., Python) which are hard to debug, and strongly typed languages ( e.g., Java) which are difficult to learn languages.
  
## Achievements

- [x]  Successfully initialized a database for the project by creating tables for the defined entities with defined relationships and data types.
- [x]  Installed Language Server Extensions in VS Code to identify syntax errors or linting issues. 
- [x] Researched and successfully set up debugging tools in VS Code for setting breakpoints and capturing errors during code execution.

## Problems (if any)

1. **Initializing Database :**
- Encountered errors while creating foreign key constraints due to data type mismatch.
- Confusion in choosing correct data types for different attributes such as price and descriptions.
2. **Incorrect syntax for Setting up Debugging:**
-  Corrected the invalid syntax as the app wasn't listed while going to "chrome://inspect" into "node --inspect-brk=9229 app.js" where 9229 is the default debugging port for running Chrome DevTools.

## Tasks for the Next Meeting:
- Wireframe designs for the home page, log-in, and sign-in page.
- Software Requirement Specification(SRS) of the project.
- Insert dummy data in the database for fetching and testing the data.
- Research and write simple test cases to check the functionality of each feature.
