### ISSUE TITLE
LogBook 3

### ISSUE THREAD

**Issue by sahilgg60** [HeroGG21/BotBazaar#3]
## Log: 3
**Meeting No:** 3
**Date:** 2024-12-11
**Start Time:** 11 A.M
**End Time:** 11:50 A.M

## Items Discussed

1.  Imperative vs. Declarative Language
     -  Discussed about the difference between imperative language (focusing on how a program operates, e.g. Java, Python) and declarative  language (what needs to be done, e.g. SQL, HTML)
2. Compiled vs. Interpreted Language:
     -  Discussed about the difference between compiled language (source code is translated into machine code, e.g. C, C++, Rust) and interpreted  language (source code is executed line-by-line, e.g. SQL, HTML)
3. Database Initialization and Sample Data:
   -  Discussed about setting up a database schema for the project.
   - Using tools and libraries like Faker and Seeder to populate the database during testing and development.
4. Test Cases:
    - Discussed about writing test cases for every failed tests which is a good example of Test Driven Development (TDD).
    
## Achievements

- [x]  Learned more about libraries and tools like faker and seeders. Created a seeder script for populating fake data into the database as sample data for testing.
- [x] Research about test cases. Installed libraries like "mocha" and "supertest" while using "chai" framework.
- [x] Write Test cases related to user model.
- [x] Document on Software Requirement Analysis (SRS)   

## Problems (if any)

1. **Fake data population:**
- Challenges: 
      -While providing value for user_id in fake data manually, auto-increment issues arise which will conflict with existing values. 
      -Taking longer time in populating large datasets. 

- Solutions:
       - Used libraries like Faker.js and sequelize methods to insert user data excluding user_id.
       - Used "bulkCreate" function for inserting multiple user data at once.

2. **Test Case Issues:**
- Challenges:
       -Test cases accidentally connected to the production database as I'm  completely new with the test cases.
       -Test cases for user authentication failed due to invalid tokens.

- Solutions:
        -Created separate database for testing i.e. testdb only.
        -Used libraries like ""jsonwebtoken" to generate test tokens for API requests. 

## Tasks for the Next Meeting:
- Further test cases for product.
- Create a Data Flow Diagram (DFD) for the project.
