### ISSUE TITLE
LogBook 4

### ISSUE THREAD

**Issue by sahilgg60** [HeroGG21/BotBazaar#4]
## Log: 4
**Meeting No:** 4
**Date:** 2024-12-24
**Start Time:** 11 A.M
**End Time:** 11:50 A.M

## Items Discussed

1.  Application Programming Interface (API)
     -  Discussed APIs shortly and recommended reading "APIs You Won't Hate" book.
2. Hyper Text Transfer Protocol (HTTP):
     - To read the documentation on HTTP by the Mozilla Developer Network(MDN) website.
     - Discussed HTTP methods briefly for CRUD operations, request, and response format.
3. HTTP Stateless:
     - Discussion on HTTP being stateless and maintaining state across multiple requests, different mechanisms like cookies, sessions, and local storage are used.
5. Socket Communication:
    - A brief discussion on socket as a two-way communication channel.
    
## Achievements

- [x]  Created a Data Flow Diagram (DFD) level 0 and 1 for the project to visualize data flow.
- [x] Created level 0 and level 1 Data Flow Diagram for the Purchase Plant process.
- [x] Created Use Case Diagrams along with High-Level Use Case Descriptions of each Use Case and Expanded Use Case Description of Purchase Plants use case.
- [x] Created a Collaboration Diagram of the Purchase Plant use case.   
- [x] Created a Sequence Diagram of the Purchase Plant use case.   

## Tasks for the Next Meeting:
- Coding for User Authentication (login, register, forgot password).
